#!/usr/bin/env python3
import os
import sys
import subprocess

def is_terminal():
    return sys.stdout.isatty()

def main():
    if is_terminal():
        os.system("python3 /opt/feliciadl/downloader.py")
    else:
        subprocess.Popen(["python3", "/opt/feliciadl/downloader_gui.py"])

if __name__ == "__main__":
    main()
