#!/usr/bin/env python3
import os
import sys
import subprocess

def is_terminal():
    return sys.stdout.isatty()

def main():
    if is_terminal():
        os.execv(sys.executable, ["python3", "/opt/feliciadl/downloader.py", *sys.argv[1:]])
    else:
        subprocess.Popen(["python3", "/opt/feliciadl/downloader_gui.py"])

if __name__ == "__main__":
    main()
